### ISSUE TITLE
[feature] Allow specifying custom user

### ISSUE THREAD

**Issue by zacharysells** [ricktbaker/opshell#1]
Hey! Thanks for making this tool, I think with a few minor enhancements it could really be beneficial to me and a lot of other people as well. 

For my use case, and I bet for a lot of others, I don't use the 'default' linux users that come with the aws AMIs. So it'd be great to be able to customize the user to connect as instead of having to choose from [ubuntu, ec2-user, centos, root]. Let me know what you think of the suggestion :)

**Comment by ricktbaker** [comment]
Thanks for the proposal.   I completely agree.   I'm actually in the same boat for a lot of my clients.   So I'm thinking of the ability to allow for importing a custom key(s), or to specify if it's just a straight up password auth.   Then give the ability to set the custom user to connect as.

Some logistics to figure out there, like what level custom users should be set at, region, organization or just overall.   So will need to figure that bit out.

**Comment by ricktbaker** [comment]
I should have this ready sometime this weekend actually for the next 0.0.7 release.

**Comment by ricktbaker** [comment]
This is now available for download in the 0.0.7 version.   When editing an organization, within the regions you can specify custom users.   If no key is imported, then it will just do password auth.
